default_language_version:
  python: python3

repos:
  # Run the Ruff linter.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.2
    hooks:
      - id: ruff

  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   rev: v0.1.2
  #   hooks:
  #     - id: ruff-format

  - repo: https://github.com/haizaar/check-pipfile-lock
    rev: v0.0.5
    hooks:
      - id: check-pipfile-lock

  - repo: local
    hooks:
      - id: validate-dashboards
        name: Validate Grafana Dashboards
        description: Ensures dashboard files are valid JSON
        entry: dev/scripts/validate_dashboards.py
        language: python
        # pass_filenames: true
        files: dashboards/
        types:
          - yaml
        additional_dependencies:
          - pyyaml
