name: CI

on:
  merge_group:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  issues: write

jobs:
  smokes-labeler:
    name: Smoke Test Label
    runs-on: ubuntu-20.04

    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: get Docker image files
        id: docker-files
        run: .github/scripts/files_require_smokes.sh >> docker-files.txt

      - name: add other required files
        id: add-files
        run: |
          echo .dockerignore >> docker-files.txt;
          echo Dockerfile >> docker-files.txt;
          echo pr_check.sh >> docker-files.txt;
          echo deploy/clowdapp.yaml >> docker-files.txt;

      - name: Show Dockerfiles
        run: cat docker-files.txt

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@d6babd6899969df1a11d14c368283ea4436bca78 # v44.5.2
        with:
          files_from_source_file: docker-files.txt

      - name: Set whether to run tests
        id: check-files
        run: |
          if [ ! -z "${{ steps.changed-files.outputs.all_changed_and_modified_files }}" ]; then
            echo "RUN_TESTS=true" >> $GITHUB_ENV
          fi

      - name: Setting smokes-required label
        if: env.RUN_TESTS == 'true'
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        continue-on-error: true
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: [ 'smokes-required' ]
            })
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'ok-to-skip-smokes'
            })

      - name: Remove smokes-required label
        if: env.RUN_TESTS != 'true'
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        continue-on-error: true
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: [ 'ok-to-skip-smokes' ]
            })
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'smokes-required'
            })
